<?php

require_once './include/header-staff.php';
require_once './include/sidebar-staff.php';

/* ==========================================================================
   1. METRICS CALCULATION
   ========================================================================== */
$staffId = $_SESSION['user_id'];

// Total Attendance by staff
$res_total_attendance = $DB->custom_query(
    "SELECT COUNT(*) AS total_attendance FROM attendance 
     WHERE user_id = '{$staffId}' AND status = 'P'"
);
$totalAttendance = ($res_total_attendance) ? (int) mysqli_fetch_assoc($res_total_attendance)['total_attendance'] : 0;

// Total Invoices generated by staff
$res_invoices_generated = $DB->read("invoices", ['where' => ['created_by' => ['=' => $staffId]]]);
$invoicesGenerated = ($res_invoices_generated) ? mysqli_num_rows($res_invoices_generated) : 0;

// Total Inquiries added by staff
$res_inquiries_added = $DB->read("inquiry", ['where' => ['created_by' => ['=' => $staffId]]]);
$inquiriesAdded = ($res_inquiries_added) ? mysqli_num_rows($res_inquiries_added) : 0;

// Total Sales done by staff
$res_total_sales = $DB->custom_query(
    "SELECT COALESCE(SUM(total), 0) AS total_sales FROM invoices 
     WHERE created_by = '{$staffId}'"
);
$totalSales = ($res_total_sales) ? (float) mysqli_fetch_assoc($res_total_sales)['total_sales'] : 0;

// Customers added by staff
$res_customers_added = $DB->read("customer", ['where' => ['created_by' => ['=' => $staffId]]]);
$customersAdded = ($res_customers_added) ? mysqli_num_rows($res_customers_added) : 0;

/* ==========================================================================
   2. WIDGETS DATA
   ========================================================================== */

// Outstanding Payments from ALL customers (for staff to see and remind)
$outstandingPayments = [];
$res_outstanding_payments = $DB->custom_query("
    SELECT
        i.id,
        i.due_date,
        i.total,
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        c.email,
        c.phone,
        COALESCE(SUM(p.amount_paid), 0) AS total_paid
    FROM invoices i
    JOIN customer c ON i.customer_id = c.id
    LEFT JOIN payments p ON i.id = p.invoice_id
    GROUP BY i.id
    HAVING i.total > total_paid
    ORDER BY i.due_date ASC
    LIMIT 5
");
if ($res_outstanding_payments) {
    while ($r = mysqli_fetch_assoc($res_outstanding_payments)) {
        $outstandingPayments[] = $r;
    }
}

// Recent Invoices generated by this staff
$recentInvoices = [];
$res_recent_invoices = $DB->custom_query(
    "SELECT i.id, i.invoice_date, i.total, 
            CONCAT(c.first_name,' ',c.last_name) AS customer
     FROM invoices i
     LEFT JOIN customer c ON c.id = i.customer_id
     WHERE i.created_by = '{$staffId}'
     ORDER BY i.id DESC LIMIT 5"
);
if ($res_recent_invoices) {
    while ($r = mysqli_fetch_assoc($res_recent_invoices)) {
        $recentInvoices[] = $r;
    }
}

// Customers added by this staff
$myCustomers = [];
$res_my_customers = $DB->read("customer", [
    'where' => ['created_by' => ['=' => $staffId]],
    'limit' => 5
]);
if ($res_my_customers) {
    while ($r = mysqli_fetch_assoc($res_my_customers)) {
        $myCustomers[] = $r;
    }
}

// Top Ranked Staff by Sales
$topStaff = [];
$res_top_staff = $DB->custom_query("
    SELECT
        u.name AS staff_name,
        u.role AS staff_role,
        COALESCE(SUM(i.total), 0) AS total_sales
    FROM invoices i
    JOIN users u ON u.id = i.created_by
    GROUP BY u.id
    ORDER BY total_sales DESC
    LIMIT 5
");
if ($res_top_staff) {
    while ($r = mysqli_fetch_assoc($res_top_staff)) {
        $topStaff[] = $r;
    }
}

// Safe echo function for HTML
function e($string)
{
    return htmlspecialchars($string, ENT_QUOTES, 'UTF-8');
}
?>

<div class="row layout-top-spacing">
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12 layout-spacing">
        <div class="widget widget-card-four">
            <div class="widget-content">
                <div class="w-header">
                    <h6 class="value">Total Attendance</h6>
                </div>
                <div class="w-content">
                    <p class="value fs-4 fw-bold"><?php echo number_format($totalAttendance) ?></p>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12 layout-spacing">
        <div class="widget widget-card-four">
            <div class="widget-content">
                <div class="w-header">
                    <h6 class="value">Invoices Generated</h6>
                </div>
                <div class="w-content">
                    <p class="value fs-4 fw-bold"><?php echo number_format($invoicesGenerated) ?></p>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12 layout-spacing">
        <div class="widget widget-card-four">
            <div class="widget-content">
                <div class="w-header">
                    <h6 class="value">Inquiries Added</h6>
                </div>
                <div class="w-content">
                    <p class="value fs-4 fw-bold"><?php echo number_format($inquiriesAdded) ?></p>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12 layout-spacing">
        <div class="widget widget-card-four">
            <div class="widget-content">
                <div class="w-header">
                    <h6 class="value">Total Sales</h6>
                </div>
                <div class="w-content">
                    <p class="value fs-4 fw-bold">₹ <?php echo number_format($totalSales, 2) ?></p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row layout-top-spacing">
    <div class="col-xl-6 col-lg-12 col-12 layout-spacing">
        <div class="widget widget-four">
            <div class="widget-heading">
                <h5 class="text-warning">Outstanding Payments (All Customers)</h5>
                <p class="text-muted">You can remind admin about these payments</p>
            </div>
            <div class="widget-content">
                <?php if (empty($outstandingPayments)) : ?>
                    <p class="text-center">No outstanding payments. Great job! 👍</p>
                <?php else: ?>
                    <?php foreach ($outstandingPayments as $payment) :
                        $pendingAmount = $payment['total'] - $payment['total_paid'];
                        $dueDate = new DateTime($payment['due_date']);
                        $today = new DateTime();
                        $isOverdue = $dueDate < $today && $dueDate->format('Y-m-d') != $today->format('Y-m-d');
                    ?>
                        <div class="d-flex justify-content-between align-items-center border-bottom pb-2 mb-2">
                            <div>
                                <span class="fw-bold"><?php echo e($payment['customer_name']); ?></span> - 
                                <a href="mailto:<?php echo e($payment['email']); ?>"><?php echo e($payment['email']); ?></a><br>
                                <small class="text-muted">
                                    Due: <?php echo date('M d, Y', strtotime($payment['due_date'])); ?>
                                    <?php if ($isOverdue): ?>
                                        <span class="badge bg-danger ms-1">Overdue</span>
                                    <?php endif; ?>
                                </small>
                            </div>
                            <strong class="text-danger">₹<?php echo number_format($pendingAmount, 2); ?></strong>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
    
    <div class="col-xl-6 col-lg-12 col-12 layout-spacing">
        <div class="widget widget-four">
            <div class="widget-heading">
                <h5>Recent Invoices Generated by You</h5>
            </div>
            <div class="widget-content">
                <?php if (empty($recentInvoices)) : ?>
                    <p class="text-center">No recent invoices created by you.</p>
                <?php else: ?>
                    <?php foreach ($recentInvoices as $inv) : ?>
                        <div class="d-flex justify-content-between align-items-center border-bottom pb-2 mb-2">
                            <span>#<?php echo e($inv['id']) ?> – <?php echo e($inv['customer']) ?></span>
                            <strong>₹ <?php echo number_format($inv['total'], 2) ?></strong>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<div class="row layout-top-spacing">
    <div class="col-xl-6 col-lg-12 col-12 layout-spacing">
        <div class="widget widget-four">
            <div class="widget-heading">
                <h5 class="text-info">Top Ranked Staff by Sales</h5>
                <p class="text-muted mb-0">Based on total sales generated (All-time)</p>
            </div>
            <div class="widget-content">
                <?php if (empty($topStaff)) : ?>
                    <p class="text-center">No sales data available to rank staff.</p>
                <?php else: ?>
                    <?php foreach ($topStaff as $k => $staff) : ?>
                        <div class="d-flex justify-content-between align-items-center border-bottom pb-2 mb-2">
                            <div>
                                <span class="fw-bold me-2"><?php echo $k + 1; ?>.</span>
                                <?php if ($staff['staff_role'] == 'admin') : ?>
                                    <span class="fw-bold"><?php echo e($staff['staff_name']); ?></span> 
                                    <span class="badge bg-primary ms-1">Admin</span>
                                <?php else: ?>
                                    <span><?php echo e($staff['staff_name']); ?></span>
                                <?php endif; ?>
                            </div>
                            <strong class="text-success">₹<?php echo number_format($staff['total_sales'], 2); ?></strong>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="col-xl-6 col-lg-12 col-12 layout-spacing">
        <div class="widget widget-four">
            <div class="widget-heading">
                <h5>Customers Added by You</h5>
            </div>
            <div class="widget-content">
                <?php if (empty($myCustomers)) : ?>
                    <p class="text-center">You have not added any customers yet.</p>
                <?php else: ?>
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Added On</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($myCustomers as $customer) : ?>
                                    <tr>
                                        <td><?php echo e($customer['first_name'] . ' ' . $customer['last_name']); ?></td>
                                        <td><?php echo e($customer['email']); ?></td>
                                        <td><?php echo e($customer['phone']); ?></td>
                                        <td><?php echo date('M d, Y', strtotime($customer['created_at'])); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php include './include/footer-staff.php'; ?>